In [7]:
import random
import numpy as np

import rpy2
from rpy2.robjects.packages import importr, data
import rpy2.robjects as ro
from rpy2.robjects import numpy2ri


In [13]:
# Sample adjacency matrix (replace this with your own matrix)
adjacency_matrix = np.array([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0]
])

def random_removal(A):
    # Number of nodes in the original matrix
    num_nodes = A.shape[0]

    # Step 1: Generate a random node to remove
    node_to_remove = random.randint(0, num_nodes - 1)

    # Step 2: Create a new adjacency matrix with the node removed
    new_adjacency_matrix = np.delete(A, node_to_remove, axis=0)
    new_adjacency_matrix = np.delete(new_adjacency_matrix, node_to_remove, axis=1)

    return new_adjacency_matrix

# Print the original and modified adjacency matrices
print("Original Adjacency Matrix:")
print(adjacency_matrix)
print("\nAdjacency Matrix with Node Removed:")
print(random_removal(adjacency_matrix))

np.savetxt('./data/adj.txt',adjacency_matrix)

Original Adjacency Matrix:
[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]

Adjacency Matrix with Node Removed:
[[0 1 1]
 [1 0 0]
 [1 0 0]]


# Random removal of nodes

In [31]:
import igraph as ig

In [32]:
ig.Erdos_Renyi(1000, 0.1)

AttributeError: module 'igraph' has no attribute 'Erdos_Renyi'

In [ ]:
def remove_n_nodes(A, n_removed):
    adj_mat = A.copy()
    for i in range(len(n_removed)):
        adj_mat = random_removal(adj_mat)

        np.savetxt(f'./data/adj_{i}.txt',adj_mat)


SyntaxError: invalid syntax (703004629.py, line 1)

In [29]:
%%R
library('igraph')
source('SuperNode.R')
#Read in some sample network data
Net=readRDS('data/As22Sample')

print(Net)

data <- as.matrix(read.table("./data/adj.txt", sep=" "))
network <- graph_from_adjacency_matrix(data, mode = c( "undirected"),    add.colnames = c(1:dim(data)) , add.rownames = c(1:dim(data)))


print(network)



#let's try 500 super nodes: plese feel free to change as you wish!
super_nodes = 10
SNOut=SuperNode(network, super_nodes)
Node2SN=array(SNOut$SNAssn)
Node2SN

IGRAPH 5f3de01 U--- 22801 48270 -- 
+ attr: id (v/n), label (v/c)
+ edges from 5f3de01:
 [1] 1--   2 1--   3 1--  11 1--  12 1--  13 1--  14 1--  16 1--  18 1--  20
[10] 1--  21 1--  24 1--  27 1--  28 1--  35 1--  36 1--  39 1--  42 1--  45
[19] 1--  46 1--  48 1--  49 1--  51 1--  53 1--  56 1--  58 1--  59 1--  61
[28] 1--  63 1--  64 1--  66 1--  80 1--  83 1--  97 1-- 123 1-- 158 1-- 187
[37] 1-- 189 1-- 219 1-- 236 1-- 296 1-- 355 1-- 371 1-- 388 1-- 427 1-- 492
[46] 1-- 546 1-- 772 1--1110 1--1183 1--1268 1--1269 1--1277 1--1280 1--1337
[55] 1--1338 1--1401 1--1452 1--1498 1--1510 1--1547 1--1555 1--1558 1--1578
[64] 1--1629 1--1673 1--1712 1--1750 1--1751 1--1754 1--1759 1--1770 1--1787
+ ... omitted several edges
This graph was created by an old(er) igraph version.
  Call upgrade_graph() on it to use with the current igraph version
  For now we convert it on the fly...
Error in if (!is.na(add.colnames)) { : the condition has length > 1
In addition: Warning message:
In 1:dim(da

RInterpreterError: Failed to parse and evaluate line 'library(\'igraph\')\nsource(\'SuperNode.R\')\n#Read in some sample network data\nNet=readRDS(\'data/As22Sample\')\n\nprint(Net)\n\ndata <- as.matrix(read.table("./data/adj.txt", sep=" "))\nnetwork <- graph_from_adjacency_matrix(data, mode = c( "undirected"),    add.colnames = c(1:dim(data)) , add.rownames = c(1:dim(data)))\n\n\nprint(network)\n\n\n\n#let\'s try 500 super nodes: plese feel free to change as you wish!\nsuper_nodes = 10\nSNOut=SuperNode(network, super_nodes)\nNode2SN=array(SNOut$SNAssn)\nNode2SN\n'.
R error message: 'Error in if (!is.na(add.colnames)) { : the condition has length > 1'
R stdout:
This graph was created by an old(er) igraph version.
  Call upgrade_graph() on it to use with the current igraph version
  For now we convert it on the fly...
Error in if (!is.na(add.colnames)) { : the condition has length > 1
In addition: Warning message:
In 1:dim(data) : numerical expression has 2 elements: only the first used

In [ ]:
import rpy2.robjects as robjects

# Access R's global environment
r = robjects.r

# Get the value of 'my_variable' from R
my_variable = list(r['Node2SN'])

print(f"Value of my_variable in R: {my_variable}")


Value of my_variable in R: [1.0, 1.0, 3.0, 4.0, 5.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 1770.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 45.0, 45.0, 46.0, 48.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 4.0, 55.0, 56.0, 57.0, 58.0, 59.0, 59.0, 61.0, 23.0, 63.0, 64.0, 34.0, 53.0, 20.0, 2367.0, 69.0, 70.0, 52.0, 72.0, 73.0, 74.0, 70.0, 3.0, 23.0, 78.0, 59.0, 80.0, 23.0, 23.0, 83.0, 3.0, 23.0, 86.0, 40.0, 23.0, 23.0, 59.0, 23.0, 23.0, 7.0, 55.0, 55.0, 23.0, 97.0, 97.0, 99.0, 23.0, 101.0, 103.0, 103.0, 23.0, 109.0, 106.0, 72.0, 108.0, 109.0, 23.0, 23.0, 112.0, 13.0, 51.0, 11.0, 23.0, 15.0, 99.0, 4.0, 23.0, 23.0, 4.0, 51.0, 23.0, 99.0, 23.0, 12432.0, 128.0, 129.0, 23.0, 23.0, 23.0, 23.0, 23.0, 55.0, 23.0, 23.0, 23.0, 27.0, 140.0, 140.0, 23.0, 39.0, 8.0, 3.0, 3.0, 4.0, 3.0, 3.0, 55.0, 151.0, 40.0, 3.0, 3.0, 4.0, 157.0, 157.0, 158.0, 158.0, 23.0, 161.0, 161.0